const router = require('express').Router();
const { auth } = require('../middleware/auth');
const orgContext = require('../middleware/orgContext');
const entitlement = require('../middleware/entitlement');
const moduleGuard = require('../middleware/moduleGuard');
const permission = require('../middleware/permission');
const { ok, created, asyncHandler } = require('../utils/response');
const service = require('../services/operationalDomains.service');
const secure = (mod, action) => [auth, orgContext, entitlement, moduleGuard(mod), permission(mod, action)];

router.post('/quality/ncrs', ...secure('quality', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createNcr(req, req.body))));
router.post('/quality/inspections/:id/disposition', ...secure('quality', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.disposeInspection(req, { ...req.body, inspection_id: req.params.id }))));
router.post('/payroll/:id/finalize', ...secure('payroll', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.finalizePayroll(req, req.params.id))));
router.post('/payroll/components', ...secure('payroll', 'can_create'), asyncHandler(async (req, res) => created(res, await service.savePayrollComponent(req, req.body))));
router.post('/payroll/overtime', ...secure('payroll', 'can_edit'), asyncHandler(async (req, res) => created(res, await service.recordPayrollOvertime(req, req.body))));
router.post('/payroll/:id/calculate', ...secure('payroll', 'can_edit'), asyncHandler(async (req, res) => ok(res, await service.calculatePayroll(req, req.params.id))));
router.post('/payroll/:id/review', ...secure('payroll', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.transitionPayroll(req, req.params.id, 'review'))));
router.post('/payroll/:id/approve', ...secure('payroll', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.transitionPayroll(req, req.params.id, 'approve'))));
router.post('/payroll/:id/lock', ...secure('payroll', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.transitionPayroll(req, req.params.id, 'lock'))));
router.post('/payroll/:id/post-to-finance', ...secure('payroll', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.postPayrollToFinance(req, req.params.id, req.body))));
router.get('/payroll/:runId/payslips/:employeeId', ...secure('payroll', 'can_view'), asyncHandler(async (req, res) => ok(res, await service.getPayslip(req, req.params.runId, req.params.employeeId))));
router.post('/finance/accounts', ...secure('finance', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createAccount(req, req.body))));
router.post('/finance/journals/:id/submit', ...secure('finance', 'can_edit'), asyncHandler(async (req, res) => ok(res, await service.submitJournal(req, req.params.id, 'submit'))));
router.post('/finance/journals/:id/approve', ...secure('finance', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.submitJournal(req, req.params.id, 'approve'))));
router.post('/finance/journals/:id/post', ...secure('finance', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.submitJournal(req, req.params.id, 'post'))));
router.get('/finance/statements/:type', ...secure('finance', 'can_view'), asyncHandler(async (req, res) => ok(res, await service.financialStatement(req, req.params.type, req.query))));
for (const [path, type] of [['/finance/gl', 'gl'], ['/finance/trial-balance', 'trial_balance'], ['/finance/p&l', 'profit_loss'], ['/finance/balance-sheet', 'balance_sheet'], ['/finance/ar-ageing', 'ar_ageing'], ['/finance/ap-ageing', 'ap_ageing']]) {
  router.get(path, ...secure('finance', 'can_view'), asyncHandler(async (req, res) => ok(res, await service.financialStatement(req, type, req.query))));
}
router.post('/finance/periods/:periodKey/close', ...secure('finance', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.closePeriod(req, req.params.periodKey))));
router.post('/finance/journals/:id/reverse', ...secure('finance', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.reverseJournal(req, req.params.id))));
router.post('/finance/documents', ...secure('finance', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createFinanceDocument(req, req.body))));
router.post('/purchase/vendor-invoices', ...secure('purchase', 'can_create'), asyncHandler(async (req, res) => {
  return created(res, await service.createFinanceDocument(req, { ...req.body, document_type: 'payable' }));
}));
router.post('/finance/expenses/:id/approve', ...secure('finance', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.transitionExpense(req, req.params.id, 'approve'))));
router.post('/finance/expenses/:id/reject', ...secure('finance', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.transitionExpense(req, req.params.id, 'reject'))));
router.post('/finance/expenses/:id/post', ...secure('finance', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.transitionExpense(req, req.params.id, 'post'))));
router.post('/finance/payables/:id/pay', ...secure('finance', 'can_edit'), asyncHandler(async (req, res) => ok(res, await service.recordVendorPayment(req, req.params.id, req.body))));
router.post('/finance/bank', ...secure('finance', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createBankTransaction(req, req.body))));
router.post('/finance/bank/:id/reconcile', ...secure('finance', 'can_edit'), asyncHandler(async (req, res) => ok(res, await service.reconcileBank(req, req.params.id))));
router.post('/gst/calculate', ...secure('gst', 'can_view'), asyncHandler(async (req, res) => ok(res, service.calculateGSTAuthoritative(req.body.items, req.org.state, req.body.customer_state))));
router.post('/gst/:type/:sourceId', ...secure('gst', 'can_create'), asyncHandler(async (req, res) => {
  const payload = service.integrationBoundary(req.params.type, req.params.sourceId, req.body);
  const [existing] = await req.orgDb.query('SELECT id,document_type,source_id,status,request_payload,response_payload,external_reference,last_error FROM government_documents WHERE document_type=? AND source_id=?', { replacements: [payload.document_type, payload.source_id] });
  if (existing[0]) return ok(res, { ...existing[0], already_queued: true });
  await req.orgDb.query('INSERT INTO government_documents(id,document_type,source_id,status,request_payload) VALUES(?,?,?,?,?)', { replacements: [require('uuid').v4(), payload.document_type, payload.source_id, payload.status, JSON.stringify(payload.request_payload)] });
  return created(res, payload);
}));
router.post('/gst/snapshots', ...secure('gst', 'can_create'), asyncHandler(async (req, res) => created(res, await service.gstSnapshot(req, req.body))));
router.post('/quality/specifications', ...secure('quality', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createQualitySpecification(req, req.body))));
router.post('/quality/parameters', ...secure('quality', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createQualityParameter(req, req.body))));
router.post('/quality/sampling-plans', ...secure('quality', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createQualitySamplingPlan(req, req.body))));
router.post('/quality/acceptance-criteria', ...secure('quality', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createQualityAcceptanceCriteria(req, req.body))));
router.post('/quality/inspections/:id/snapshots', ...secure('quality', 'can_view'), asyncHandler(async (req, res) => created(res, await service.createInspectionSnapshot(req, req.params.id, req.body.payload || req.body))));
router.post('/quality/ncrs/:id/transition', ...secure('quality', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.transitionNcr(req, req.params.id, req.body))));
router.post('/hr/departments', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createDepartment(req, req.body))));
router.post('/hr/designations', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createHrMaster(req, 'designation', req.body))));
router.post('/hr/employment-types', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createHrMaster(req, 'employment_type', req.body))));
router.post('/hr/document-types', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createHrMaster(req, 'document_type', req.body))));
router.post('/hr/locations', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createLocation(req, req.body))));
router.post('/hr/grades', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createGrade(req, req.body))));
router.post('/hr/shifts', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createShift(req, req.body))));
router.post('/hr/calendars', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createCalendar(req, req.body))));
router.post('/hr/attendance/corrections', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createAttendanceCorrection(req, req.body))));
router.post('/hr/attendance/corrections/:id/approve', ...secure('hr', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.approveAttendanceCorrection(req, req.params.id, req.body))));
router.get('/hr/employees/:id/360', ...secure('hr', 'can_view'), asyncHandler(async (req, res) => ok(res, await service.getEmployee360(req, req.params.id))));
router.post('/hr/leave/policies', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createLeavePolicy(req, req.body))));
router.post('/hr/leave/accrual-rules', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createLeaveAccrualRule(req, req.body))));
router.post('/hr/leave/holidays', ...secure('hr', 'can_create'), asyncHandler(async (req, res) => created(res, await service.createHoliday(req, req.body))));
router.post('/hr/leave/validate', ...secure('hr', 'can_view'), asyncHandler(async (req, res) => ok(res, await service.validateLeaveRequest(req, req.body))));
router.post('/hr/leave/:id/approve', ...secure('hr', 'can_approve'), asyncHandler(async (req, res) => ok(res, await service.approveLeaveRequest(req, req.params.id, req.body))));
router.post('/hr/leave/balance-transactions', ...secure('hr', 'can_edit'), asyncHandler(async (req, res) => created(res, await service.recordLeaveBalanceTransaction(req, req.body))));
router.get('/reports/analytics/:key', ...secure('reports', 'can_view'), asyncHandler(async (req, res) => ok(res, await service.report(req, req.params.key, req.query))));
module.exports = router;
